/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "video-background": "#020617",
        "background": "#f7f9fb",
        "outline-variant": "#c6c6cd",
        "deep-navy": "#0F172A",
        "slate-600": "#475569",
        "on-tertiary-container": "#0090a9",
        "on-tertiary-fixed": "#001f26",
        "on-primary": "#ffffff",
        "outline": "#76777d",
        "surface": "#f7f9fb",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-fixed": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "primary-container": "#131b2e",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#001f26",
        "surface-container-low": "#f2f4f6",
        "primary-fixed": "#dae2fd",
        "vibrant-cyan": "#06B6D4",
        "secondary-fixed": "#d5e3fd",
        "primary": "#000000",
        "status-success": "#10B981",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#0d1c2f",
        "tertiary": "#000000",
        "inverse-primary": "#bec6e0",
        "secondary": "#515f74",
        "surface-tint": "#565e74",
        "on-primary-container": "#7c839b",
        "secondary-container": "#d5e3fd",
        "on-surface-variant": "#45464d",
        "surface-variant": "#e0e3e5",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#b9c7e0",
        "on-secondary-fixed-variant": "#3a485c",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-secondary-container": "#57657b",
        "status-warning": "#F59E0B",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#acedff",
        "surface-container": "#eceef0"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter-desktop": "24px",
        "gutter-mobile": "16px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "base": "4px"
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "mono-data": ["JetBrains Mono"]
      },
      fontSize: {
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "mono-data": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
